# Site settings
title: "Jessie Scotson's Resume"
description: "Customer service & support specialist"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Jessie Scotson"
resume_title:                   "Customer service & support specialist"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "cv@pasquet.co"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "07792985916"
resume_contact_address:         "Cheshire, England"

resume_header_contact_info:     "Cheshire, England • 1 • cv-jessie@pasquet.co"
display_header_contact_info:    "false"

resume_header_intro: |
  I am a highly motivated conscientious individual who is charismatic and loves to help people. I work well on
  my own or as part of a team. I am determined and eager to learn new skills.

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  # resume_github_url:            "https://github.com/winterscar"
  # # resume_twitter_url:           "http://twitter.com/jglovier"
  # # resume_dribbble_url:          "https://dribbble.com/jag"
  # # resume_facebook_url:          "insert Facebook URL here"
  # resume_linkedin_url:          "https://www.linkedin.com/in/mathieu-pasquet-956386b5"
  # # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "https://cv.pasquet.co"
  # resume_medium_url:            "https://medium.com/@mt.psqt"
resume_print_social_links:      false

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
